version: "3.3"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp_volume:/var/www/html
    networks:
      - app-network
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/html
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: always
  

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /Users/araiteb/Desktop/ince/inception/srcs/volume/db
  wp_volume:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /Users/araiteb/Desktop/ince/inception/srcs/volume/wp
