FROM debian:buster

RUN apt-get update
RUN apt-get install -y mariadb-server

EXPOSE 3306

RUN sed -i 's/.*bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf
COPY ./tools /var/www/

RUN chmod +x /var/www/db_script.sh

CMD [ "/var/www/db_script.sh" ]