FROM debian:buster
RUN  apt-get update
RUN apt-get install -y php7.3\
						php-fpm\
						php-mysql\
                        wget\
						curl
COPY ./tools  /var/
EXPOSE 9000
RUN chmod +x /var/script.sh
ENTRYPOINT [ "/var/script.sh" ]
# CMD [""]

