FROM debian:buster
RUN  apt-get update
RUN apt-get install -y mariadb-server
COPY ./tools/db.sql  /var/
COPY ./tools/logs.sh  /var/
EXPOSE 3306
RUN chmod -R +x /var/logs.sh
RUN service mysql start && mysql < /var/db.sql
RUN sh < /var/logs.sh
CMD ["mysqld"]