FROM debian:buster
RUN apt-get update
RUN apt-get install -y mariadb-server
RUN sed -i 's/.*bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf
EXPOSE 3306
COPY ./tools/db.sh /
RUN chmod +x /db.sh
RUN service mysql start
CMD ["mysqld"]