FROM debian:buster
RUN apt-get update
RUN apt-get install -y mariadb-server
RUN sed -i 's/.*bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf
COPY ./tools/db.sql /var/
EXPOSE 3306
RUN service mysql start && mysql < /var/db.sql
CMD [ "mysqld" ]